services:
  cometbft-1:
    image: vs
    privileged: true
    container_name: cometbft-1
    ports:
      - "8000:8000"
    volumes:
      - ./node1/cometbft:/root/.cometbft
      - ./node1/data:/root/zcash-vote-server/data
      - ./node1/db:/root/zcash-vote-server/db
      - ./node1/tailscale-data:/var/lib/tailscale
    environment:
      - TS_AUTHKEY
      - NODE=node1
    stdin_open: true
    tty: true
